global using NUnit.Framework;
global using MediatR;
global using Microsoft.AspNetCore.Mvc;
global using Moq;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using Zip.Installments.Api.Controllers;
global using Zip.Installments.Command.Commands;
global using Zip.Installments.Contract.Response;
global using Zip.Installments.Domain.Entities;
global using Zip.Installments.Query.Queries;
global using Zip.InstallmentsService.Interface;
global using Microsoft.EntityFrameworkCore;
global using static Zip.Installments.Command.Commands.CreatePaymentInstallmentPlanCommand;
global using Zip.Installments.Infrastructure.Context;
global using AutoFixture;
global using static Zip.Installments.Query.Queries.GetPaymentInstallmentPlanByIdQuery;
global using Zip.Installments.Contract.Request;
global using Zip.InstallmentsService.Service;
global using Microsoft.Extensions.Logging;
global using Zip.Installments.Api.ModelValidation;